name: macos-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
      - name: Install Dependencies
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install \
            cairo \
            freetype \
            glib \
            gobject-introspection \
            graphite2 \
            icu4c \
            meson \
            ninja \
            pkg-config
      - name: Install Python Dependencies
        run: pip3 install -r .ci/requirements.txt --require-hashes
      - name: Setup Meson
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig"
          ccache --version
          meson setup build \
            -Dauto_features=enabled \
            -Ddocs=disabled \
            -Dchafa=disabled \
            -Dcoretext=enabled \
            -Dgraphite=enabled \
            -Doptimization=2 \
            -Db_coverage=true \
      - name: Build
        run: meson compile -Cbuild
      - name: Test
        run: meson test --print-errorlogs -Cbuild
      - name: Generate Coverage
        run: ninja -Cbuild coverage-xml
      - name: Upload Coverage
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
        with:
          file: build/meson-logs/coverage.xml
